// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSCMS.Data;

#nullable disable

namespace PSCMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522153652_AddStateToFacility")]
    partial class AddStateToFacility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSCMS.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("PSCMS.Models.GoodsReceiptNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("GrnNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InspectedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("OverallNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GrnNumber")
                        .IsUnique();

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.ToTable("GoodsReceiptNotes");
                });

            modelBuilder.Entity("PSCMS.Models.GoodsReceiptNoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrnId");

                    b.HasIndex("ProductId");

                    b.ToTable("GoodsReceiptNoteItems");
                });

            modelBuilder.Entity("PSCMS.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("FacilityId", "ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PSCMS.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PSCMS.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PSCMS.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresColdChain")
                        .HasColumnType("boolean");

                    b.Property<double?>("StorageTemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("StorageTemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir Disoproxil Fumarate/Lamivudine/Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab TDF/3TC/DTG (300/300/50MG) X 90",
                            RequiresColdChain = false,
                            Strength = "300/300/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir Disoproxil Fumarate/Lamivudine/Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab TDF/3TC/DTG (300/300/50MG) X 30",
                            RequiresColdChain = false,
                            Strength = "300/300/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir Disoproxil Fumarate/Lamivudine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab TDF/3TC (300/300MG) X 30",
                            RequiresColdChain = false,
                            Strength = "300/300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab ABC/3TC (600/300MG) X 30",
                            RequiresColdChain = false,
                            Strength = "600/300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "Tab ABC/3TC (120/60MG) X 30",
                            RequiresColdChain = false,
                            Strength = "120/60mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "Tab LPV/r (200/50MG) X 120",
                            RequiresColdChain = false,
                            Strength = "200/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Tab ATV/r (300/100MG) X 30",
                            RequiresColdChain = false,
                            Strength = "300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab DTG 50MG X 30",
                            RequiresColdChain = false,
                            Strength = "50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "Tab DTG 10MG X 90",
                            RequiresColdChain = false,
                            Strength = "10mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Suspension",
                            GenericName = "Zidovudine",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Susp AZT (50MG/5mL) 240mL",
                            RequiresColdChain = false,
                            Strength = "50mg/5mL",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Suspension",
                            GenericName = "Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Susp NVP (50MG/5mL) 100mL",
                            RequiresColdChain = false,
                            Strength = "50mg/5mL",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "Tab INH 300MG",
                            RequiresColdChain = false,
                            Strength = "300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "Tab INH 100MG X 100",
                            RequiresColdChain = false,
                            Strength = "100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid/Rifapentine",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "Tab 3HP",
                            RequiresColdChain = false,
                            Strength = "300/300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid/Pyridoxine/Cotrimoxazole",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tabs INH/Pyridoxine/Cotrimoxazole 300/25/960mg",
                            RequiresColdChain = false,
                            Strength = "300/25/960mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Sulfamethoxazole/Trimethoprim",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab Co-trimoxazole 960MG X 500",
                            RequiresColdChain = false,
                            Strength = "960mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Sulfamethoxazole/Trimethoprim",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab Co-trimoxazole 120MG X 1000",
                            RequiresColdChain = false,
                            Strength = "120mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Vaginal Pessary",
                            GenericName = "Clotrimazole",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Clotrimazole Vaginal Pessary 100MG x 6",
                            RequiresColdChain = false,
                            Strength = "100mg",
                            Unit = "Pessaries",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Metronidazole",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tab Metronidazole 200MG x 1000",
                            RequiresColdChain = false,
                            Strength = "200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Injection",
                            GenericName = "Benzathine Benzylpenicillin",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Inj Benzathine benzyl penicilline 2.4MIU X 1",
                            RequiresColdChain = false,
                            Strength = "2.4MIU",
                            Unit = "Vials",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Erythromycin",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Tabs Erythromycin 500mg x 10",
                            RequiresColdChain = false,
                            Strength = "500mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Drops",
                            GenericName = "Nystatin",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Oral Nystatin drop",
                            RequiresColdChain = false,
                            Strength = "100,000 IU/mL",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Fluconazole",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Tab Fluconazole 50MG X 10",
                            RequiresColdChain = false,
                            Strength = "50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Injection",
                            GenericName = "Amphotericin B (Liposomal)",
                            IsActive = true,
                            MinimumStockLevel = 20,
                            Name = "Liposomal Amphotericin B 50mg",
                            RequiresColdChain = false,
                            Strength = "50mg",
                            Unit = "Vials",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Flucytosine",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Tabs Flucytosine 500mg X 100",
                            RequiresColdChain = false,
                            Strength = "500mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            Category = "ARVs & OIs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Solution",
                            GenericName = "Podophyllotoxin",
                            IsActive = true,
                            MinimumStockLevel = 20,
                            Name = "Podophyllotoxin Solution 0.5% w/v",
                            RequiresColdChain = false,
                            Strength = "0.5% w/v",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            Category = "Preventive Supplies",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Device",
                            GenericName = "Male Condom",
                            IsActive = true,
                            MinimumStockLevel = 1000,
                            Name = "Male Condoms pcs",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Pieces",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            Category = "Preventive Supplies",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Device",
                            GenericName = "Female Condom",
                            IsActive = true,
                            MinimumStockLevel = 500,
                            Name = "Female Condom pcs",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Pieces",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            Category = "Preventive Supplies",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Gel",
                            GenericName = "Lubricant",
                            IsActive = true,
                            MinimumStockLevel = 200,
                            Name = "Lubricant",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "HIV Rapid Test - Determine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "DETERMINE X 100",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "HIV Rapid Test - UniGold",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "UNIGOLD X 20",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "HIV Rapid Test - STAT-PAK",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "STAT-PAK X 20",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000033"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "Cryptococcal Antigen Test",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Cryptococcal Antigen Lateral Flow Assay (CrAg-LFA) X 50",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000034"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "HIV Recency Test - Asante",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Recency Test Kit (Asante) X 100",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000035"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "Urine TB LF-LAM",
                            IsActive = true,
                            MinimumStockLevel = 25,
                            Name = "Urine TB LF-LAM X 25",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000036"),
                            Category = "RTKs",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Test Kit",
                            GenericName = "CD4 Test - Visitect",
                            IsActive = true,
                            MinimumStockLevel = 25,
                            Name = "Visitect X 25",
                            RequiresColdChain = false,
                            Strength = "N/A",
                            Unit = "Tests",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreparedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("PSCMS.Models.ShipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("PSCMS.Models.StockLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("NewStock")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousStock")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "ChangedAt");

                    b.ToTable("StockLedger");
                });

            modelBuilder.Entity("PSCMS.Models.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationFacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceFacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationFacilityId");

                    b.HasIndex("SourceFacilityId");

                    b.HasIndex("TransferNumber")
                        .IsUnique();

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("PSCMS.Models.StockTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferId");

                    b.ToTable("StockTransferItems");
                });

            modelBuilder.Entity("PSCMS.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 18, 22, 37, 6, 0, DateTimeKind.Utc),
                            Email = "admin@pscms.org",
                            IsActive = true,
                            PasswordHash = "$2a$11$3key4UV6y0c.JjCXNE94Te3PF.NIAFSsi286X7wJX/jiaoFyoK3VG",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 3, 18, 22, 37, 6, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PSCMS.Models.WeeklyStockSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklyStockSnapshots");
                });

            modelBuilder.Entity("PSCMS.Models.GoodsReceiptNote", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PSCMS.Models.GoodsReceiptNoteItem", b =>
                {
                    b.HasOne("PSCMS.Models.GoodsReceiptNote", "GoodsReceiptNote")
                        .WithMany("Items")
                        .HasForeignKey("GrnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceiptNote");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSCMS.Models.Inventory", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Inventories")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Orders")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("PSCMS.Models.OrderItem", b =>
                {
                    b.HasOne("PSCMS.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSCMS.Models.PasswordResetToken", b =>
                {
                    b.HasOne("PSCMS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Shipments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PSCMS.Models.ShipmentItem", b =>
                {
                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Shipment", "Shipment")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PSCMS.Models.StockLedger", b =>
                {
                    b.HasOne("PSCMS.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("PSCMS.Models.StockTransfer", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "DestinationFacility")
                        .WithMany()
                        .HasForeignKey("DestinationFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Facility", "SourceFacility")
                        .WithMany()
                        .HasForeignKey("SourceFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationFacility");

                    b.Navigation("SourceFacility");
                });

            modelBuilder.Entity("PSCMS.Models.StockTransferItem", b =>
                {
                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.StockTransfer", "StockTransfer")
                        .WithMany("Items")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockTransfer");
                });

            modelBuilder.Entity("PSCMS.Models.User", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("PSCMS.Models.WeeklyStockSnapshot", b =>
                {
                    b.HasOne("PSCMS.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("PSCMS.Models.Facility", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Orders");

                    b.Navigation("Shipments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PSCMS.Models.GoodsReceiptNote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("PSCMS.Models.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("PSCMS.Models.StockTransfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
