// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSCMS.Data;

#nullable disable

namespace PSCMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412152756_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSCMS.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("PSCMS.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("FacilityId", "ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PSCMS.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PSCMS.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Lamivudine/Emtricitabine+Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "3TC/FTC(300/300mg)+ATV/r(300/100mg)",
                            Strength = "300/300mg+300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Lamivudine/Emtricitabine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "3TC/FTC(300/300mg)+EFV(600mg)",
                            Strength = "300/300mg+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Lamivudine/Emtricitabine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "3TC/FTC(300/300mg)+NVP(200mg)",
                            Strength = "300/300mg+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine/Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(120mg)/3TC(60mg)/DTG(50mg)",
                            Strength = "120/60/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(120mg)/3TC(60mg)+DTG(10mg)",
                            Strength = "120/60mg+10mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(120mg)/3TC(60mg)+DTG(50mg)",
                            Strength = "120/60mg+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(120mg)+3TC(60mg)+DTG(50mg)",
                            Strength = "120+60+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "ABC(120mg)+3TC(60mg)+LPV/r(100mg/25mg)",
                            Strength = "120+60+100/25mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "ABC(120mg)+3TC(60mg)+LPV/r(40mg/10mg)",
                            Strength = "120+60+40/10mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution+Tablet",
                            GenericName = "Abacavir+Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "ABC(20mg/ml)+3TC(300mg)+DTG50(50mg)",
                            Strength = "20mg/ml+300+50mg",
                            Unit = "Pack",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution",
                            GenericName = "Abacavir+Didanosine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 30,
                            Name = "ABC(20mg/ml)+DDI(10mg/ml)+LPV/r(80/20mg/ml)",
                            Strength = "20+10+80/20mg/ml",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution+Tablet",
                            GenericName = "Abacavir+Emtricitabine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "ABC(20mg/ml)+FTC(200mg)+DTG(50mg)",
                            Strength = "20mg/ml+200+50mg",
                            Unit = "Pack",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "ABC(300mg)+3TC(150mg)+EFV(600mg)",
                            Strength = "300+150+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "ABC(300mg)+3TC(150mg)+LPV/r(200/50mg)",
                            Strength = "300+150+200/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "ABC(300mg)+3TC(150mg)+NVP(200mg)",
                            Strength = "300+150+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 120,
                            Name = "ABC(600mg)/3TC(300mg)+DTG(50mg)",
                            Strength = "600/300mg+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 120,
                            Name = "ABC(600mg)+3TC(300mg)+DTG(50mg)",
                            Strength = "600+300+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir/Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(60mg)/3TC(30mg)+DTG(50mg)",
                            Strength = "60/30mg+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(60mg)+3TC(30mg)+DTG(50mg)",
                            Strength = "60+30+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(60mg)+3TC(30mg)+EFV(200mg)",
                            Strength = "60+30+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "ABC(60mg)+3TC(30mg)+LPV/r(40/10mg)",
                            Strength = "60+30+40/10mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution",
                            GenericName = "Abacavir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 30,
                            Name = "ABC(60mg)+3TC(30mg)+LPV/r(80/20mg/ml)",
                            Strength = "60+30+80/20mg/ml",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Abacavir+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "ABC(60mg)+3TC(30mg)+NVP(50mg)",
                            Strength = "60+30+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution+Capsule",
                            GenericName = "Zidovudine+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "AZT(10mg/ml)+3TC(10mg/ml)+EFV(200mg)",
                            Strength = "10+10mg/ml+200mg",
                            Unit = "Pack",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution",
                            GenericName = "Zidovudine+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "AZT(10mg/ml)+3TC(10mg/ml)+NVP(10mg/ml)",
                            Strength = "10+10+10mg/ml",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Abacavir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "AZT(300mg)+3TC(150mg)+ABC(300mg)",
                            Strength = "300+150+300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "AZT(300mg)+3TC(150mg)+ATV/r(300mg/100mg)",
                            Strength = "300+150+300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT(300mg)+3TC(150mg)+EFV(600mg)",
                            Strength = "300+150+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "AZT(300mg)+3TC(150mg)+LPV/r(200/50mg)",
                            Strength = "300+150+200/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT(300mg)+3TC(150mg)+NVP(200mg)",
                            Strength = "300+150+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Tenofovir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "AZT(300mg)+3TC(150mg)+TDF(300mg)",
                            Strength = "300+150+300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Tenofovir+Lamivudine+Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "AZT(300mg)+TDF(300mg)+3TC(150mg)+ATV/r(300mg/100mg)",
                            Strength = "300+300+150+300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000033"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "AZT(60mg)+3TC(30mg)+LPV/r(40/10mg)",
                            Strength = "60+30+40/10mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000034"),
                            Category = "ARV - Paediatric 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Solution",
                            GenericName = "Zidovudine+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 30,
                            Name = "AZT(60mg)+3TC(30mg)+LPV/r(80/20mg/ml)",
                            Strength = "60+30+80/20mg/ml",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000035"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine/Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT/3TC(300/150mg)+EFV(200mg)",
                            Strength = "300/150+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000036"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine/Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT/3TC(300/150mg)+EFV(600mg)",
                            Strength = "300/150+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000037"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine/Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT/3TC(300/150mg)+NVP(200mg)",
                            Strength = "300/150+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000038"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Zidovudine/Lamivudine/Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "AZT/3TC/NVP(300/150/200mg)",
                            Strength = "300/150/200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000039"),
                            Category = "OI Prophylaxis",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Oral Suspension",
                            GenericName = "Sulfamethoxazole/Trimethoprim",
                            IsActive = true,
                            MinimumStockLevel = 50,
                            Name = "Cotrimoxazole 240mg/5ml",
                            Strength = "240mg/5ml",
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000040"),
                            Category = "OI Prophylaxis",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Sulfamethoxazole/Trimethoprim",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Cotrimoxazole 480mg",
                            Strength = "480mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000041"),
                            Category = "OI Prophylaxis",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Sulfamethoxazole/Trimethoprim",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Cotrimoxazole 960mg",
                            Strength = "960mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000042"),
                            Category = "ARV - Adult 1st Line (Legacy)",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Stavudine+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "d4T(30mg)+3TC(150mg)+EFV(600mg)",
                            Strength = "30+150+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000043"),
                            Category = "ARV - Adult 1st Line (Legacy)",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Stavudine+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "d4T(30mg)+3TC(150mg)+NVP(200mg)",
                            Strength = "30+150+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000044"),
                            Category = "ARV - Paediatric 1st Line (Legacy)",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Stavudine/Lamivudine/Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 40,
                            Name = "d4T/3TC/NVP(6/30/50mg)",
                            Strength = "6/30/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000045"),
                            Category = "ARV - Individual ARV",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Dolutegravir",
                            Strength = "50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000046"),
                            Category = "ARV - Individual ARV",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Dolutegravir(50mg)",
                            Strength = "50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000047"),
                            Category = "Supportive Care",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Folic Acid",
                            IsActive = true,
                            MinimumStockLevel = 200,
                            Name = "Folic Acid 5mg",
                            Strength = "5mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000048"),
                            Category = "TB Preventive Therapy",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "Isoniazid-(INH) 100mg",
                            Strength = "100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000049"),
                            Category = "TB Preventive Therapy",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "Isoniazid-(INH) 300mg",
                            Strength = "300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000050"),
                            Category = "TB Preventive Therapy",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "Isoniazid 100mg",
                            Strength = "100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000051"),
                            Category = "TB Preventive Therapy",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid/Rifapentine",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "Isoniazid and Rifapentine-(3HP)",
                            Strength = "3HP combo",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000052"),
                            Category = "TB Preventive Therapy",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Isoniazid/Pyridoxine/Cotrimoxazole",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Isoniazid(300mg)/Pyridoxine(25mg)/Cotrimoxazole(960mg)",
                            Strength = "300/25/960mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000053"),
                            Category = "ARV - Individual ARV",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Lamivudine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Lamivudine",
                            Strength = "150mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000054"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir/Lamivudine/Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 200,
                            Name = "TDF(300mg)/3TC(300mg)/DTG(50mg)",
                            Strength = "300/300/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000055"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "TDF(300mg)+3TC(150mg)+ATV/r(300/100mg)",
                            Strength = "300+150+300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000056"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "TDF(300mg)+3TC(150mg)+LPV/r(200/50mg)",
                            Strength = "300+150+200/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000057"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Atazanavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "TDF(300mg)+3TC(300mg)+ATV/r(300/100mg)",
                            Strength = "300+300+300/100mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000058"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 120,
                            Name = "TDF(300mg)+3TC(300mg)+EFV(600mg)",
                            Strength = "300+300+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000059"),
                            Category = "ARV - Adult 2nd Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Lopinavir/Ritonavir",
                            IsActive = true,
                            MinimumStockLevel = 60,
                            Name = "TDF(300mg)+3TC(300mg)+LPV/r(200/50mg)",
                            Strength = "300+300+200/50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000060"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "TDF(300mg)+3TC(300mg)+NVP(200mg)",
                            Strength = "300+300+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000061"),
                            Category = "ARV - Paediatric 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Lamivudine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 80,
                            Name = "TDF(300mg)+3TC(30mg)+DTG(50mg)",
                            Strength = "300+30+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000062"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir+Emtricitabine+Dolutegravir",
                            IsActive = true,
                            MinimumStockLevel = 150,
                            Name = "TDF(300mg)+FTC(200mg)+DTG(50mg)",
                            Strength = "300+200+50mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000063"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir/Emtricitabine+Efavirenz",
                            IsActive = true,
                            MinimumStockLevel = 120,
                            Name = "TDF/FTC(300/200mg)+EFV(600mg)",
                            Strength = "300/200+600mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000064"),
                            Category = "ARV - Adult 1st Line",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir/Emtricitabine+Nevirapine",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "TDF/FTC(300/200mg)+NVP(200mg)",
                            Strength = "300/200+200mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000065"),
                            Category = "ARV - Individual ARV",
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DosageForm = "Tablet",
                            GenericName = "Tenofovir Disoproxil",
                            IsActive = true,
                            MinimumStockLevel = 100,
                            Name = "Tenofovir",
                            Strength = "300mg",
                            Unit = "Tablets",
                            UpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreparedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("PSCMS.Models.ShipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("PSCMS.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 18, 22, 37, 6, 0, DateTimeKind.Utc),
                            Email = "admin@pscms.org",
                            IsActive = true,
                            PasswordHash = "$2a$11$3key4UV6y0c.JjCXNE94Te3PF.NIAFSsi286X7wJX/jiaoFyoK3VG",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 3, 18, 22, 37, 6, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PSCMS.Models.Inventory", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Inventories")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Orders")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("PSCMS.Models.OrderItem", b =>
                {
                    b.HasOne("PSCMS.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Shipments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PSCMS.Models.ShipmentItem", b =>
                {
                    b.HasOne("PSCMS.Models.Product", "Product")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSCMS.Models.Shipment", "Shipment")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PSCMS.Models.User", b =>
                {
                    b.HasOne("PSCMS.Models.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("PSCMS.Models.Facility", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Orders");

                    b.Navigation("Shipments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PSCMS.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("PSCMS.Models.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("ShipmentItems");
                });

            modelBuilder.Entity("PSCMS.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentItems");
                });
#pragma warning restore 612, 618
        }
    }
}
